name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  generate_matrix:
    name: Set matrix
    runs-on: self-hosted
    outputs:
      sdks: ${{ steps.find_targets.outputs.sdks }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt

      - name: Set targets
        id: find_targets
        run: |
          # sdks
          # JSON='['
          # FIRST=1

          # while read -r line;
          # do
          #   ARCH=$(echo "$line" | cut -d " " -f 1)

          #   [[ $FIRST -ne 1 ]] && JSON="$JSON"','
          #   FIRST=0

          #   JSON="$JSON"'{"arch":"'"$ARCH"'"}'
          # done <<< $(perl ./scripts/dump-target-info.pl architectures 2>/dev/null)

          JSON='[{"arch":"x86_64"}]'
          echo -e "\n---- sdks ----\n"
          echo "$JSON"
          echo -e "\n---- sdks ----\n"
          echo "sdks=$JSON" >> "$GITHUB_OUTPUT"

  build:
    name: Build for ${{ matrix.arch }}
    runs-on: self-hosted
    needs: generate_matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate_matrix.outputs.sdks) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch upstream git reversion
        id: op_version
        run: echo sha=$(cat .nvchecker/sha) >> $GITHUB_OUTPUT

      - name: Build Package
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-main
          V: s
          IGNORE_ERRORS: n m y
          NO_DEFAULT_FEEDS: 1
          EXTRA_FEEDS: >-
            src-git-full|base|https://github.com/openwrt/openwrt.git
            src-git|packages|https://github.com/openwrt/packages.git^${{ steps.op_version.outputs.sha }}
          PACKAGES: cloudflared

      - name: Upload Output Folder
        uses: actions/upload-artifact@v4
        with:
          name: cloudflared-${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages/cloudflared_*.ipk

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: self-hosted
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.ipk"
